channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - python>=3.6
  - numpy 
  - pandas 
  - numexpr>=2.3.1 
  - khmer>=2.1 
  - sphinx_rtd_theme>=0.1.9 
  - pytest 
  - pytest-runner 
  - doit>=0.29.0 
  - matplotlib 
  - shmlast 
  - infernal 
  - hmmer 
  - transdecoder=3.0.1 
  - last
  - busco=3.0.2 
  - parallel 
  - bioconductor-seqlogo
  - pip:
    - git+https://github.com/dib-lab/dammit
