channels:
  - conda-forge
  - bioconda
  - nodefaults
dependencies:
  - bwa =0.7.17
  - bwa-mem2 =2.2.1
  - bwa-meme =1.0.5
  - samtools =1.16.1
  - samblaster =0.1.26
  - mbuffer =20160228
  - picard-slim =2.27.4
