channels:
  - conda-forge
  - bioconda
  - nodefaults
dependencies:
  - bioconductor-mofa2 =1.16.0
  - bioconductor-basilisk =1.18.0
  - r-base =4.5.2
  # - r-tidyverse # TODO lookup
  # - r-data.table =1.17.8 # TODO remove maybe
  - r-arrow =22.0.0
  - mofapy2 =0.7.0
  - python =3.14.2
