channels:
  - conda-forge
  - bioconda
  - nodefaults
dependencies:
  - freebayes =1.3.10
  - bcftools =1.22
  - vcflib =1.0.14
  - htslib =1.22.1
  - parallel =20250622
  - bedtools =2.31.1
  - sed =4.9
  - snakemake-wrapper-utils =0.7.2
