channels:
  - conda-forge
  - bioconda
  - nodefaults
dependencies:
  - freebayes =1.3.8
  - bcftools =1.21
  - vcflib =1.0.12
  - htslib =1.21
  - parallel =20241222
  - bedtools =2.31.1
  - sed =4.8
  - snakemake-wrapper-utils =0.6.2
