channels:
  - conda-forge
  - bioconda
  - nodefaults
dependencies:
  - bowtie2 =2.5.4
  - bcftools =1.20
  - spades =3.15.5
  - samtools =1.20
  - pilon =1.24
  - racon =1.5.0
  - blast =2.15.0
  - unicycler =0.5.0
