channels:
  - conda-forge
  - bioconda
  - nodefaults
dependencies:
  - bowtie2 =2.5.4
  - bcftools =1.20
  - spades =4.0.0
  - samtools =1.20
  - pilon =1.24
  - racon =1.5.0
  - blast =2.16.0
  - unicycler =0.5.1
