channels:
  - conda-forge
  - bioconda
  - nodefaults
dependencies:
  - bowtie2 =2.4.5
  - bcftools =1.16
  - spades =3.15.5
  - samtools =1.16.1
  - pilon =1.24
  - racon =1.5.0
  - blast =2.13.0
  - unicycler =0.5.0
